engines:
  cppcheck:
    enabled: true
    config:
      check: all
      language: c
      stds:
        - c11
      platform: unix64
  fixme:
    enabled: true
ratings:
  paths: []
exclude_paths:
  - test/
