sudo: false
language: c
compiler: gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang
    - libcunit1
    - libcunit1-dev
    - libcurl4-openssl-dev
    - libjansson-dev
script: make test
