sudo: false
language: c
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq
  - sudo apt-get install -y -qq libcunit1 libcunit1-dev libcurl4-openssl-dev libjansson-dev
script: autoreconf -f -i && CFLAGS=-Werror ./configure && make && make check
