sudo: false
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libcunit1
      - libcunit1-dev
      - libcurl4-openssl-dev
      - libjansson-dev
script: ./configure && make && make check
