sudo: false
language: cpp
compiler: gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libcunit1
    - libcunit1-dev
    - libcurl4-openssl-dev
    - libjansson-dev
script: make test
